refactor(icons): use standard octicons
gitify-app/gitify pull request #885
Opened 2024-03-15 11:26 UTC by setchy

Replaces the refresh, settings, logout and add account icons with those from the octicons prime design system used extensively throughout our experience.

Note: if we can find a suitable replacement for the Quit icon from https://primer.style/foundations/icons then we'll be 100% octicon powered.

| | Light | Dark |
|-|-|-|
| **_Before_** | ![Screenshot 2024-03-15 at 7 21 30 AM](https://github.com/gitify-app/gitify/assets/386277/daf68afb-0016-4c76-866b-ec0483d98602) |  ![Screenshot 2024-03-15 at 7 21 38 AM](https://github.com/gitify-app/gitify/assets/386277/d69265c6-f9a3-43ec-bd2d-0967a46b8e41) |
| **_After_**  | ![Screenshot 2024-03-15 at 7 20 30 AM](https://github.com/gitify-app/gitify/assets/386277/1f7b76ba-c93e-43d0-83f1-1cd540e58aef) | ![Screenshot 2024-03-15 at 7 20 21 AM](https://github.com/gitify-app/gitify/assets/386277/7b1344d2-7f5a-421d-a443-55bc79ce7bac)  |

2024-03-18 11:15 UTC, bmulholland commented
For the Quit icon, how about just an X? I know we use it elsewhere, but it's pretty standard for "close this app" and is in Octicons.

2024-03-18 14:45 UTC, afonsojramos commented
I'm glad that we're now grouping them in one PR, because I truly dislike these new icons. I understand the objective here, but they just look plain ugly and the app just doesn't look right with the change.

2024-03-18 15:09 UTC, afonsojramos commented
> I think that grouping these changes all in one PR truly gave us a new perspective in what the changes would entail.
> 
> From a UI cohesiveness perspective, they seem as if they don't belong, mostly the ones in the bottom bar. The size of the bottom bar also seems to have grown, but that seems like a simple mistake.
> 
> Food for thought: Maybe one alternative would be to go away with the bottom bar and adding a profile image with a dropdown with these three options, where the icons would be accompanied with a descriptive text. What do you think?

Rephrased for the sake of being more clear about the issues I see with the current change.

2024-03-18 16:15 UTC, setchy commented
> The size of the bottom bar also seems to have grown, but that seems like a simple mistake.

yes, that had stuck out to me too. adjust

2024-03-18 16:17 UTC, setchy commented
> Food for thought: Maybe one alternative would be to go away with the bottom bar and adding a profile image with a dropdown with these three options, where the icons would be accompanied with a descriptive text. What do you think?

i'm not a huge fan of putting these an additional click away (behind a dropdown)

2024-03-18 16:19 UTC, setchy commented
> From a UI cohesiveness perspective, they seem as if they don't belong, mostly the ones in the bottom bar.

Personal taste perhaps.  🤷  

imho, this switch to fully adopt Octicons / Primer Design System makes Gitify feel more consistent and unified 🙃

2024-03-19 01:58 UTC, afonsojramos requested changes
If I am the minority here, I am open to conceding. But in that case, I think I'd switch for the no fill X, since we're not using Fill anywhere else 🧐

2024-03-19 01:58 UTC, afonsojramos commented on src/components/Sidebar.tsx
> +            <XCircleFillIcon size={16} aria-label="Quit Gitify" />
```suggestion
            <XCircleIcon size={16} aria-label="Quit Gitify" />
```

2024-03-19 01:58 UTC, afonsojramos commented on src/components/Sidebar.tsx
> +  XCircleFillIcon,
```suggestion
  XCircleIcon,
```

2024-03-20 15:59 UTC, merged